language: groovy
os: linux
dist: bionic
arch: amd64
sudo: required
services: docker

before_install:
    - echo "Installing nextflow"
    - wget -qO- https://get.nextflow.io | bash 
    - echo "Building docker container"
    - docker build . --file ./Dockerfile --tag variantcalling
    - sudo mv nextflow /usr/local/bin

script:
    - nextflow run ./main.nf --align all --reads "./CIN*R{1,2}" --ref "./ref.fa" --fastp_min_base_quality 15 --fastp_max_percent_low_qual_base 40 --verbose -with-docker variantcalling:latest --travis true;

after_success:
    - echo "CI build of variantcalling pipeline succeeded"

after_failure: 
    - echo "CI build of variantcalling pipeline failed"
