language: groovy
os: linux
dist: bionic
arch: amd64
sudo: required
services: docker

before_install:
    - echo "This is the first attempt at .travis.yml for variantcalling"
    - echo "This is an attempt to build the Dockerfile environment"
    - docker build . --file ./Dockerfile --tag varcall
    - docker run varcall --name varcall

script:
    - docker ps -a
    - nextflow run ./main.nf -with-docker varcall

after_success:
    - echo "Your ci build of Dockerfile has succeeded"

after_failure: 
    - echo "Your ci build of Dockerfile has failed"
