name: variantcalling-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bbmap=38.18
  - bcftools=1.10.2
  - bowtie2=2.3.5.1
  - bwa=0.7.17
  - fastp=0.20.1
  - fastqc=0.11.9
  - freebayes=1.3.2
  - htslib=1.10.2
  - minimap2=2.17
  - openjdk=8.0.192
  - pip=20.1.1
  - python=3.7.6
  - samtools=1.10
  - seqtk=1.3
  - snippy=4.6.0
  - snpeff=4.5covid19
  - pip:
    - biopython==1.77
    - numpy==1.18.5
    - pandas==1.0.5
    - vcf-consensus-builder==0.1.0
